version: '3'
services:
  back-end:
    build: ./back-end
    container_name: foodOrderingAppBack
    ports:
      - "5000:5000"
    volumes:
      - ./back-end:/home/app
      - /home/app/node_modules
    environment:
      CONNECTIONSTRING: postgresql://user:${PG_PASSWORD}@db:5432
      # - CREDS=//Your Firebase service account goes here 
    depends_on:
      - db

  front-end:
    build: ./front-end
    container_name: foodOrderingAppFront
    ports:
      - "3000:3000"
    volumes:
      - ./front-end:/home/app
      - /home/app/node_modules

  db:
    image: 'postgres'
    container_name: foodOrderingAppDb
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - pgdata:/var/lib/postgresql/data
      
volumes:
  pgdata:
