version: "3"
services:
    back-end:
        build:
            context: ./back-end
            dockerfile: Dockerfile.prod
        expose:
            - 5000
        environment:
            CONNECTIONSTRING: postgresql://user:${PG_PASSWORD}@db:5432
            CREDS: ${CREDS}
        depends_on:
            - db

    front-end:
        build:
            context: ./front-end
            dockerfile: Dockerfile.prod
        ports:
            - 80:80
        depends_on:
            - back-end

    db:
        image: postgres:16-alpine
        environment:
            POSTGRES_USER: "user"
            POSTGRES_PASSWORD: ${PG_PASSWORD}
        volumes:
            - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
