# Stage 1: Build
FROM node:14 AS build

WORKDIR /app


COPY package*.json ./

RUN npm install

COPY . ./

RUN npm run build


# Stage 2: Deploy
FROM nginx:1.19.0-alpine

COPY --from=build /app/build /usr/share/nginx/html

COPY nginx/nginx.conf.prod /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
