name: Frontend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'front-end/**'  
      - '.github/workflows/frontend.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'front-end/**'
      - '.github/workflows/frontend.yml'

jobs:
  build-and-lint:
    runs-on: ubuntu-latest



    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: "Cache Node.js modules"
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('front-end/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: npm ci, lint, build, and test
        working-directory: front-end
        run: |
          npm ci
          npm run lint
          npm run build
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
      
      - name: Upload build artifacts
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v3
        with:
          name: react-build
          path: ./front-end/build

  deploy:
    if: github.event_name == 'push'  
    runs-on: ubuntu-latest
    needs: build-and-lint
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: react-build
          path: ./downloaded-build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "./downloaded-build"  
          skip_app_build: true
